package openhorizon

import (
	"fmt"
	"strings"
)

// Logging function to provide a prefix for log records generated by this plugin.
var ohlog = func(v interface{}) string {
	return fmt.Sprintf("openhorizon auth plugin: %v", v)
}

// The input is org/url, output is (org, url).
// assume no `/` in the org
func SplitOrgSpecUrl(org_url string) (string, string) {
	if org_url == "" {
		return "", ""
	} else {
		s := strings.SplitN(org_url, "/", 2)
		if len(s) == 1 {
			return "", s[0]
		} else {
			return s[0], s[1]
		}
	}
}
